2019-06-02 19:30:58,113 ERROR: Exception on /explore [GET] [in /home/pilovec/.virtualenvs/microblog_env/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/pilovec/.virtualenvs/microblog_env/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pilovec/.virtualenvs/microblog_env/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pilovec/.virtualenvs/microblog_env/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pilovec/.virtualenvs/microblog_env/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/pilovec/.virtualenvs/microblog_env/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pilovec/.virtualenvs/microblog_env/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pilovec/.virtualenvs/microblog_env/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/pilovec/www/microblog/app/routes.py", line 128, in explore
    return render_template('index.html', title='Explore', posts=posts)
  File "/home/pilovec/.virtualenvs/microblog_env/lib/python3.6/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/pilovec/.virtualenvs/microblog_env/lib/python3.6/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/pilovec/.virtualenvs/microblog_env/lib/python3.6/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/pilovec/.virtualenvs/microblog_env/lib/python3.6/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/pilovec/.virtualenvs/microblog_env/lib/python3.6/site-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/home/pilovec/.virtualenvs/microblog_env/lib/python3.6/site-packages/jinja2/environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/home/pilovec/.virtualenvs/microblog_env/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pilovec/.virtualenvs/microblog_env/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/pilovec/www/microblog/app/templates/index.html", line 22, in template
    {% endblock %}
  File "/home/pilovec/.virtualenvs/microblog_env/lib/python3.6/site-packages/jinja2/environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "/home/pilovec/.virtualenvs/microblog_env/lib/python3.6/site-packages/jinja2/parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/home/pilovec/.virtualenvs/microblog_env/lib/python3.6/site-packages/jinja2/parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "/home/pilovec/.virtualenvs/microblog_env/lib/python3.6/site-packages/jinja2/parser.py", line 144, in parse_statement
    self.fail_unknown_tag(token.value, token.lineno)
  File "/home/pilovec/.virtualenvs/microblog_env/lib/python3.6/site-packages/jinja2/parser.py", line 97, in fail_unknown_tag
    return self._fail_ut_eof(name, self._end_token_stack, lineno)
  File "/home/pilovec/.virtualenvs/microblog_env/lib/python3.6/site-packages/jinja2/parser.py", line 90, in _fail_ut_eof
    self.fail(' '.join(message), lineno)
  File "/home/pilovec/.virtualenvs/microblog_env/lib/python3.6/site-packages/jinja2/parser.py", line 59, in fail
    raise exc(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endblock'.
2019-06-02 19:31:44,687 INFO: Microblog startup [in /home/pilovec/www/microblog/app/__init__.py:43]
2019-06-02 19:31:49,799 ERROR: Exception on /explore [GET] [in /home/pilovec/.virtualenvs/microblog_env/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/pilovec/.virtualenvs/microblog_env/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pilovec/.virtualenvs/microblog_env/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pilovec/.virtualenvs/microblog_env/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pilovec/.virtualenvs/microblog_env/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/pilovec/.virtualenvs/microblog_env/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pilovec/.virtualenvs/microblog_env/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pilovec/.virtualenvs/microblog_env/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/pilovec/www/microblog/app/routes.py", line 128, in explore
    return render_template('index.html', title='Explore', posts=posts)
  File "/home/pilovec/.virtualenvs/microblog_env/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/pilovec/.virtualenvs/microblog_env/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/pilovec/.virtualenvs/microblog_env/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/pilovec/.virtualenvs/microblog_env/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/pilovec/.virtualenvs/microblog_env/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pilovec/.virtualenvs/microblog_env/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/pilovec/www/microblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/pilovec/www/microblog/app/templates/base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
  File "/home/pilovec/www/microblog/app/templates/index.html", line 5, in block "content"
    {{ form.hidden_tag() }}
  File "/home/pilovec/.virtualenvs/microblog_env/lib/python3.6/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2019-06-02 19:31:58,768 INFO: Microblog startup [in /home/pilovec/www/microblog/app/__init__.py:43]
